city_streets["achinsk"] = {builds: [{street: "1-й мкр.", build: "29"},
{street: "1-й мкр.", build: "30"},
{street: "1-й мкр.", build: "31"},
{street: "1-й мкр.", build: "32"},
{street: "1-й мкр.", build: "33"},
{street: "1-й мкр.", build: "34"},
{street: "1-й мкр.", build: "35"},
{street: "1-й мкр.", build: "36"},
{street: "1-й мкр.", build: "37"},
{street: "1-й мкр.", build: "38"},
{street: "1-й мкр.", build: "39"},
{street: "1-й мкр.", build: "40"},
{street: "1-й мкр.", build: "41"},
{street: "1-й мкр.", build: "42"},
{street: "1-й мкр.", build: "42А"},
{street: "1-й мкр.", build: "46"},
{street: "1-й мкр.", build: "48"},
{street: "1-й мкр.", build: "50"},
{street: "1-й мкр.", build: "50А"},
{street: "24-й квартал", build: "1"},
{street: "24-й квартал", build: "10"},
{street: "24-й квартал", build: "11"},
{street: "24-й квартал", build: "2"},
{street: "24-й квартал", build: "3"},
{street: "24-й квартал", build: "8"},
{street: "24-й квартал", build: "9"},
{street: "25-й квартал", build: "1"},
{street: "25-й квартал", build: "2"},
{street: "28-й квартал", build: "1"},
{street: "28-й квартал", build: "12"},
{street: "28-й квартал", build: "2"},
{street: "28-й квартал", build: "3"},
{street: "28-й квартал", build: "6"},
{street: "28-й квартал", build: "7"},
{street: "28-й квартал", build: "8"},
{street: "28-й квартал", build: "9"},
{street: "2-й мкр.", build: "1"},
{street: "2-й мкр.", build: "11"},
{street: "2-й мкр.", build: "13"},
{street: "2-й мкр.", build: "14"},
{street: "2-й мкр.", build: "18"},
{street: "2-й мкр.", build: "19"},
{street: "2-й мкр.", build: "2"},
{street: "2-й мкр.", build: "20"},
{street: "2-й мкр.", build: "22"},
{street: "2-й мкр.", build: "23"},
{street: "2-й мкр.", build: "24"},
{street: "2-й мкр.", build: "25"},
{street: "2-й мкр.", build: "26"},
{street: "2-й мкр.", build: "3"},
{street: "2-й мкр.", build: "4"},
{street: "2-й мкр.", build: "5"},
{street: "2-й мкр.", build: "6"},
{street: "2-й мкр.", build: "7"},
{street: "2-й мкр.", build: "8"},
{street: "2-й мкр.", build: "9"},
{street: "3-й мкр.", build: "16"},
{street: "3-й мкр.", build: "17"},
{street: "3-й мкр.", build: "3"},
{street: "3-й мкр.", build: "30"},
{street: "3-й мкр.", build: "40"},
{street: "3-й мкр.", build: "22"},
{street: "3-й мкр.", build: "24"},
{street: "3-й мкр.", build: "25"},
{street: "3-й мкр.", build: "1"},
{street: "3-й мкр.", build: "10"},
{street: "3-й мкр.", build: "11"},
{street: "3-й мкр.", build: "12"},
{street: "3-й мкр.", build: "13"},
{street: "3-й мкр.", build: "14"},
{street: "3-й мкр.", build: "15"},
{street: "3-й мкр.", build: "15А"},
{street: "3-й мкр.", build: "2"},
{street: "3-й мкр.", build: "22А"},
{street: "3-й мкр.", build: "23"},
{street: "3-й мкр.", build: "26"},
{street: "3-й мкр.", build: "27"},
{street: "3-й мкр.", build: "28"},
{street: "3-й мкр.", build: "2А"},
{street: "3-й мкр.", build: "31А"},
{street: "3-й мкр.", build: "32"},
{street: "3-й мкр.", build: "33"},
{street: "3-й мкр.", build: "34"},
{street: "3-й мкр.", build: "35"},
{street: "3-й мкр.", build: "36"},
{street: "3-й мкр.", build: "37"},
{street: "3-й мкр.", build: "4"},
{street: "3-й мкр.", build: "5"},
{street: "3-й мкр.", build: "6"},
{street: "3-й мкр.", build: "8"},
{street: "3-й мкр.", build: "9"},
{street: "4-й мкр.", build: "4"},
{street: "4-й мкр.", build: "6А"},
{street: "4-й мкр.", build: "8А"},
{street: "4-й мкр.", build: "1"},
{street: "4-й мкр.", build: "10"},
{street: "4-й мкр.", build: "11"},
{street: "4-й мкр.", build: "12"},
{street: "4-й мкр.", build: "13"},
{street: "4-й мкр.", build: "14"},
{street: "4-й мкр.", build: "15"},
{street: "4-й мкр.", build: "16"},
{street: "4-й мкр.", build: "17"},
{street: "4-й мкр.", build: "18"},
{street: "4-й мкр.", build: "19"},
{street: "4-й мкр.", build: "2"},
{street: "4-й мкр.", build: "20"},
{street: "4-й мкр.", build: "21"},
{street: "4-й мкр.", build: "22"},
{street: "4-й мкр.", build: "22А"},
{street: "4-й мкр.", build: "23"},
{street: "4-й мкр.", build: "24"},
{street: "4-й мкр.", build: "25"},
{street: "4-й мкр.", build: "29"},
{street: "4-й мкр.", build: "3"},
{street: "4-й мкр.", build: "34"},
{street: "4-й мкр.", build: "5"},
{street: "4-й мкр.", build: "6"},
{street: "4-й мкр.", build: "7"},
{street: "4-й мкр.", build: "8"},
{street: "4-й мкр.", build: "9"},
{street: "5-й мкр.", build: "21А"},
{street: "5-й мкр.", build: "5"},
{street: "5-й мкр.", build: "10"},
{street: "5-й мкр.", build: "11"},
{street: "5-й мкр.", build: "12"},
{street: "5-й мкр.", build: "16"},
{street: "5-й мкр.", build: "17"},
{street: "5-й мкр.", build: "18"},
{street: "5-й мкр.", build: "19"},
{street: "5-й мкр.", build: "20"},
{street: "5-й мкр.", build: "21"},
{street: "5-й мкр.", build: "22"},
{street: "5-й мкр.", build: "22А"},
{street: "5-й мкр.", build: "22Б"},
{street: "5-й мкр.", build: "24"},
{street: "5-й мкр.", build: "25"},
{street: "5-й мкр.", build: "26"},
{street: "5-й мкр.", build: "27"},
{street: "5-й мкр.", build: "28"},
{street: "5-й мкр.", build: "29"},
{street: "5-й мкр.", build: "30"},
{street: "5-й мкр.", build: "31"},
{street: "5-й мкр.", build: "32"},
{street: "5-й мкр.", build: "33"},
{street: "5-й мкр.", build: "34"},
{street: "5-й мкр.", build: "35"},
{street: "5-й мкр.", build: "35А"},
{street: "5-й мкр.", build: "36"},
{street: "5-й мкр.", build: "39"},
{street: "5-й мкр.", build: "40"},
{street: "5-й мкр.", build: "41"},
{street: "5-й мкр.", build: "43"},
{street: "5-й мкр.", build: "45"},
{street: "5-й мкр.", build: "6"},
{street: "5-й мкр.", build: "7"},
{street: "5-й мкр.", build: "8"},
{street: "6-й мкр.", build: "10"},
{street: "6-й мкр.", build: "11"},
{street: "6-й мкр.", build: "12"},
{street: "6-й мкр.", build: "13"},
{street: "6-й мкр.", build: "14"},
{street: "6-й мкр.", build: "15"},
{street: "6-й мкр.", build: "2"},
{street: "6-й мкр.", build: "3"},
{street: "6-й мкр.", build: "4"},
{street: "6-й мкр.", build: "5"},
{street: "6-й мкр.", build: "6"},
{street: "6-й мкр.", build: "7"},
{street: "6-й мкр.", build: "8"},
{street: "6-й мкр.", build: "9"},
{street: "7-й мкр.", build: "1"},
{street: "7-й мкр.", build: "14"},
{street: "7-й мкр.", build: "15"},
{street: "7-й мкр.", build: "2"},
{street: "7-й мкр.", build: "4"},
{street: "7-й мкр.", build: "5"},
{street: "7-й мкр.", build: "6"},
{street: "7-й мкр.", build: "7"},
{street: "7-й мкр.", build: "8"},
{street: "7-й мкр.", build: "9"},
{street: "8-й мкр.", build: "1"},
{street: "8-й мкр.", build: "11"},
{street: "8-й мкр.", build: "12"},
{street: "8-й мкр.", build: "13"},
{street: "8-й мкр.", build: "14"},
{street: "8-й мкр.", build: "19"},
{street: "8-й мкр.", build: "2"},
{street: "8-й мкр.", build: "20"},
{street: "8-й мкр.", build: "3"},
{street: "8-й мкр.", build: "3А"},
{street: "8-й мкр.", build: "4"},
{street: "8-й мкр.", build: "7"},
{street: "9-й мкр.", build: "10"},
{street: "9-й мкр.", build: "11"},
{street: "9-й мкр.", build: "12"},
{street: "9-й мкр.", build: "14"},
{street: "9-й мкр.", build: "2"},
{street: "9-й мкр.", build: "21"},
{street: "9-й мкр.", build: "22"},
{street: "9-й мкр.", build: "23"},
{street: "9-й мкр.", build: "24"},
{street: "9-й мкр.", build: "25"},
{street: "9-й мкр.", build: "26"},
{street: "9-й мкр.", build: "27"},
{street: "9-й мкр.", build: "28"},
{street: "9-й мкр.", build: "29"},
{street: "9-й мкр.", build: "3"},
{street: "9-й мкр.", build: "30"},
{street: "9-й мкр.", build: "4"},
{street: "9-й мкр.", build: "5"},
{street: "9-й мкр.", build: "6"},
{street: "9-й мкр.", build: "7"},
{street: "9-й мкр.", build: "8"},
{street: "9-й мкр.", build: "9"},
{street: "Авиатор", build: "24"},
{street: "Авиатор", build: "25"},
{street: "Авиатор", build: "26"},
{street: "Авиатор", build: "27"},
{street: "Восточный мкр.", build: "10"},
{street: "Восточный мкр.", build: "11"},
{street: "Восточный мкр.", build: "12"},
{street: "Восточный мкр.", build: "13"},
{street: "Восточный мкр.", build: "14"},
{street: "Восточный мкр.", build: "15"},
{street: "Восточный мкр.", build: "15А"},
{street: "Восточный мкр.", build: "16"},
{street: "Восточный мкр.", build: "20"},
{street: "Восточный мкр.", build: "21"},
{street: "Восточный мкр.", build: "22"},
{street: "Восточный мкр.", build: "23"},
{street: "Восточный мкр.", build: "24"},
{street: "Восточный мкр.", build: "25"},
{street: "Восточный мкр.", build: "26"},
{street: "Восточный мкр.", build: "3"},
{street: "Восточный мкр.", build: "5"},
{street: "Восточный мкр.", build: "6"},
{street: "Восточный мкр.", build: "7"},
{street: "Восточный мкр.", build: "8"},
{street: "Восточный мкр.", build: "9"},
{street: "Восточный мкр.", build: "28"},
{street: "Восточный мкр.", build: "29"},
{street: "Восточный мкр.", build: "30"},
{street: "Восточный мкр.", build: "31"},
{street: "Восточный мкр.", build: "32"},
{street: "Восточный мкр.", build: "33"},
{street: "Восточный мкр.", build: "34"},
{street: "Восточный мкр.", build: "35"},
{street: "Восточный мкр.", build: "36"},
{street: "Восточный мкр.", build: "37"},
{street: "Восточный мкр.", build: "37А"},
{street: "Восточный мкр.", build: "38"},
{street: "Восточный мкр.", build: "39"},
{street: "Восточный мкр.", build: "40"},
{street: "Восточный мкр.", build: "41"},
{street: "Восточный мкр.", build: "44"},
{street: "Восточный мкр.", build: "44А"},
{street: "Восточный мкр.", build: "46"},
{street: "Восточный мкр.", build: "48"},
{street: "Восточный мкр.", build: "48А"},
{street: "Восточный мкр.", build: "49"},
{street: "Восточный мкр.", build: "50"},
{street: "Восточный мкр.", build: "51"},
{street: "Восточный мкр.", build: "53"},
{street: "Восточный мкр.", build: "55"},
{street: "Восточный мкр.", build: "56"},
{street: "Восточный мкр.", build: "57"},
{street: "Восточный мкр.", build: "58"},
{street: "Восточный мкр.", build: "59"},
{street: "Восточный мкр.", build: "60"},
{street: "Восточный мкр.", build: "61"},
{street: "Восточный мкр.", build: "62"},
{street: "Индустриальная улица", build: "13"},
{street: "Индустриальная улица", build: "15"},
{street: "Индустриальная улица", build: "16Б"},
{street: "Индустриальная улица", build: "17"},
{street: "Индустриальная улица", build: "19"},
{street: "Квартал 7Б", build: "7"},
{street: "Квартал 7Б", build: "1"},
{street: "Квартал 7Б", build: "10"},
{street: "Квартал 7Б", build: "11"},
{street: "Квартал 7Б", build: "2"},
{street: "Квартал 7Б", build: "3"},
{street: "Квартал 7Б", build: "4"},
{street: "Квартал 7Б", build: "5"},
{street: "Квартал 7Б", build: "8"},
{street: "Квартал 7Б", build: "9"},
{street: "квартал Политехникума", build: "1"},
{street: "квартал Политехникума", build: "2"},
{street: "МПС", build: "1"},
{street: "Набережная улица", build: "30"},
{street: "Поселок строителей", build: "13"},
{street: "Поселок строителей", build: "14"},
{street: "Поселок строителей", build: "19"},
{street: "Поселок строителей", build: "25"},
{street: "Поселок строителей", build: "26"},
{street: "Привокзальная улица", build: "14"},
{street: "Привокзальная улица", build: "16"},
{street: "Привокзальная улица", build: "38"},
{street: "Привокзальный мкр.", build: "15"},
{street: "Привокзальный мкр.", build: "23"},
{street: "Привокзальный мкр.", build: "3"},
{street: "Привокзальный мкр.", build: "30"},
{street: "Привокзальный мкр.", build: "1"},
{street: "Привокзальный мкр.", build: "17"},
{street: "Привокзальный мкр.", build: "2"},
{street: "Привокзальный мкр.", build: "3"},
{street: "Привокзальный мкр.", build: "4"},
{street: "Привокзальный мкр.", build: "5"},
{street: "Привокзальный мкр.", build: "6"},
{street: "Садовая улица", build: "3"},
{street: "улица 40 лет ВЛКСМ", build: "10"},
{street: "улица Гагарина", build: "10"},
{street: "улица Гагарина", build: "38"},
{street: "улица Гагарина", build: "5А"},
{street: "улица Давыдова", build: "1"},
{street: "улица Давыдова", build: "2"},
{street: "улица Декабристов", build: "21"},
{street: "улица Декабристов", build: "25"},
{street: "улица Декабристов", build: "25А"},
{street: "улица Декабристов", build: "27"},
{street: "улица Декабристов", build: "42"},
{street: "улица Декабристов", build: "44"},
{street: "улица Дружбы Народов", build: "11"},
{street: "улица Дружбы Народов", build: "2"},
{street: "улица Дружбы Народов", build: "7"},
{street: "улица Дружбы Народов", build: "9"},
{street: "улица Зверева", build: "10"},
{street: "улица Зверева", build: "8"},
{street: "улица Кирова", build: "10"},
{street: "улица Кирова", build: "17"},
{street: "улица Кирова", build: "19"},
{street: "улица Кирова", build: "21"},
{street: "улица Кирова", build: "23"},
{street: "улица Кирова", build: "27"},
{street: "улица Кирова", build: "36"},
{street: "улица Кирова", build: "38"},
{street: "улица Кирова", build: "40"},
{street: "улица Кирова", build: "40А"},
{street: "улица Кирова", build: "41"},
{street: "улица Кирова", build: "42"},
{street: "улица Кирова", build: "44"},
{street: "улица Кирова", build: "46"},
{street: "улица Кирова", build: "48"},
{street: "улица Кирова", build: "50"},
{street: "улица Кирова", build: "52"},
{street: "улица Кирова", build: "54"},
{street: "улица Кирова", build: "56"},
{street: "улица Кирова", build: "6"},
{street: "улица Кирова", build: "8"},
{street: "улица Кравченко", build: "1"},
{street: "улица Кравченко", build: "7"},
{street: "улица Культуры", build: "2"},
{street: "улица Культуры", build: "3"},
{street: "улица Культуры", build: "4"},
{street: "улица Культуры", build: "5"},
{street: "улица Культуры", build: "6"},
{street: "улица Культуры", build: "7"},
{street: "улица Манкевича", build: "16"},
{street: "улица Манкевича", build: "18"},
{street: "улица Манкевича", build: "20"},
{street: "улица Манкевича", build: "31"},
{street: "улица Манкевича", build: "33"},
{street: "улица Мира", build: "1"},
{street: "улица Мира", build: "11"},
{street: "улица Мира", build: "12"},
{street: "улица Мира", build: "13"},
{street: "улица Мира", build: "14"},
{street: "улица Мира", build: "5"},
{street: "улица Мира", build: "9"},
{street: "улица Назарова", build: "15"},
{street: "улица Назарова", build: "17"},
{street: "улица Назарова", build: "24"},
{street: "улица Назарова", build: "28"},
{street: "улица Свердлова", build: "101"},
{street: "улица Свердлова", build: "33А"},
{street: "улица Свердлова", build: "74"},
{street: "улица Строителей", build: "12"},
{street: "улица Строителей", build: "17"},
{street: "улица Фрунзе", build: "10"},
{street: "улица Фрунзе", build: "12"},
{street: "улица Фрунзе", build: "7"},
{street: "улица Фрунзе", build: "9"},
{street: "улица Чкалова", build: "12"},
{street: "улица Чкалова", build: "16"},
{street: "улица Чкалова", build: "18"},
{street: "Восточный мкр.", build: "1"},
{street: "Восточный мкр.", build: "17"},
{street: "Восточный мкр.", build: "4"},
{street: "7-й мкр.", build: "10"},
{street: "7-й мкр.", build: "3"},],
streets: [{street: "1-й мкр."},
{street: "24-й квартал"},
{street: "25-й квартал"},
{street: "28-й квартал"},
{street: "2-й мкр."},
{street: "3-й мкр."},
{street: "4-й мкр."},
{street: "5-й мкр."},
{street: "6-й мкр."},
{street: "7-й мкр."},
{street: "8-й мкр."},
{street: "9-й мкр."},
{street: "Авиатор"},
{street: "Восточный мкр."},
{street: "Индустриальная улица"},
{street: "Квартал 7Б"},
{street: "квартал Политехникума"},
{street: "МПС"},
{street: "Набережная улица"},
{street: "Поселок строителей"},
{street: "Привокзальная улица"},
{street: "Привокзальный мкр."},
{street: "Садовая улица"},
{street: "улица 40 лет ВЛКСМ"},
{street: "улица Гагарина"},
{street: "улица Давыдова"},
{street: "улица Декабристов"},
{street: "улица Дружбы Народов"},
{street: "улица Зверева"},
{street: "улица Кирова"},
{street: "улица Кравченко"},
{street: "улица Культуры"},
{street: "улица Манкевича"},
{street: "улица Мира"},
{street: "улица Назарова"},
{street: "улица Свердлова"},
{street: "улица Строителей"},
{street: "улица Фрунзе"},
{street: "улица Чкалова"},
]}
