city_streets["belovo"] = {builds: [{street: "1-Я-БОЕВАЯ", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я-БОЕВАЯ", build: "36 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я-БОЕВАЯ", build: "38 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я-БОЕВАЯ", build: "42 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я-БОЕВАЯ", build: "44 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я-БОЕВАЯ", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "104 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "105 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "16 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "20 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "20А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "24 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "25 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "26 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "3 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "67 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "68 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "69 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "70 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "71 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "72 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "73 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "74 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "75 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "76 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "77 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "78 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "79 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "80 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "81 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "82 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "83 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "84 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "85 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "86 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "93 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "93А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3-Й-микрорайон", build: "94 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "95 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "97 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3-Й-микрорайон", build: "98 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "6-Й-микрорайон", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "БЕЛОВСКАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БЕЛОВСКАЯ", build: "2Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БЕЛОВСКАЯ", build: "2к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВЕСЕННИЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВЕСЕННИЙ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВОЛОШИНОЙ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВОЛОШИНОЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Волошиной", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ДОВАТОРА", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДОВАТОРА", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЖЕЛЕЗНОДОРОЖНАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Железнодорожная", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЖЕЛЕЗНОДОРОЖНАЯ", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЖЕЛЕЗНОДОРОЖНАЯ", build: "30 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Железнодорожная", build: "32 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "40 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "54 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная", build: "56 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЖЕЛЕЗНОДОРОЖНАЯ", build: "9А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАХОВСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КЛУБНЫЙ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОЗЛОВА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "14к.А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "1к.Б || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЛЕНИНА", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "26к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "28 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЛЕНИНА", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "32к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "36к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "36к.В || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "36к.Г || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "41 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЛЕНИНА", build: "42 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "49 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЛЕНИНА", build: "59 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "61 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина", build: "67А || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "ETTH"},
{street: "ЛЕНИНА", build: "67к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЛЮКСЕМБУРГ", build: "34к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЮКСЕМБУРГ", build: "34к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЮКСЕМБУРГ", build: "34к.Г || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Маркса", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "МОРОЗОВА", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОРОЗОВА", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Московская", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Московская", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "НОВОГОДНЯЯ", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ОКТЯБРЬСКАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ОКТЯБРЬСКАЯ", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская", build: "27 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "29 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "31 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "35 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "37 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "39 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "41 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ОКТЯБРЬСКАЯ", build: "43 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОКТЯБРЬСКАЯ", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская", build: "47 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "51 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "53 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "55 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "59 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "63 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ПОЛЯРНАЯ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПОЧТОВЫЙ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПОЧТОВЫЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПОЧТОВЫЙ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОЛЕТАРСКАЯ", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОЛЕТАРСКАЯ", build: "1к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "32 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "33 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "35 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "36 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "37 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "38 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "39 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "40 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "41В || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "41к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "41к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "42 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "43 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "45 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "46 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "47 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "48 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "49 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "50 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "51 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "53 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "55 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "56 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "58 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "62 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "63 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "СОВЕТСКАЯ", build: "67 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "69 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "71 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКИЙ", build: "1к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "2Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВЫЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СПОРТИВНЫЙ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТЕЛЬМАНА", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Толстого", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ТОЛСТОГО", build: "15к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Толстого", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ХАЛТУРИНА", build: "34в || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ХМЕЛЬНИЦКОГО", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЦИНКЗАВОДСКОЙ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЦИНКЗАВОДСКОЙ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЦИНКЗАВОДСКОЙ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской", build: "3 || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Цинкзаводской", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Цинкзаводской", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЦИНКЗАВОДСКОЙ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЧКАЛОВА", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧКАЛОВА", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная", build: "10к.А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮБИЛЕЙНАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮБИЛЕЙНАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮБИЛЕЙНАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮНОСТИ", build: "10А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮНОСТИ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮНОСТИ", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности", build: "22 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "ЮНОСТИ", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},,],
streets: [{street: "1-Я-БОЕВАЯ"},
{street: "3-Й-микрорайон"},
{street: "6-Й-микрорайон"},
{street: "БЕЛОВСКАЯ"},
{street: "ВЕСЕННИЙ"},
{street: "ВОЛОШИНОЙ"},
{street: "ДОВАТОРА"},
{street: "ЖЕЛЕЗНОДОРОЖНАЯ"},
{street: "КАХОВСКАЯ"},
{street: "КЛУБНЫЙ"},
{street: "КОЗЛОВА"},
{street: "Ленина"},
{street: "ЛЮКСЕМБУРГ"},
{street: "Маркса"},
{street: "МОРОЗОВА"},
{street: "Московская"},
{street: "НОВОГОДНЯЯ"},
{street: "Октябрьская"},
{street: "ПОЛЯРНАЯ"},
{street: "ПОЧТОВЫЙ"},
{street: "ПРОЛЕТАРСКАЯ"},
{street: "СОВЕТСКАЯ"},
{street: "СОВЕТСКИЙ"},
{street: "СОСНОВЫЙ"},
{street: "СПОРТИВНЫЙ"},
{street: "ТЕЛЬМАНА"},
{street: "Толстого"},
{street: "ХАЛТУРИНА"},
{street: "ХМЕЛЬНИЦКОГО"},
{street: "Цинкзаводской"},
{street: "ЧКАЛОВА"},
{street: "Юбилейная"},
{street: "ЮНОСТИ"},
]};
