city_streets["belovo"] = {builds: [{street: "1-Я Боевая ул", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я Боевая ул", build: "36 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я Боевая ул", build: "38 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я Боевая ул", build: "42 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я Боевая ул", build: "44 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-Я Боевая ул", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "104 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "105 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "16 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "20 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "20А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "24 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "25 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "26 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "3 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "67 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "68 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "69 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "70 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "71 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "72 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "73 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "74 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "75 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "76 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "77 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "78 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "79 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "80 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "81 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "82 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "83 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "84 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "85 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "86 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "93 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "93А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "3 Й-микрорайон ул", build: "94 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "95 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "97 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "3 Й-микрорайон ул", build: "98 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "6 Й микрорайон ул", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Беловская ул", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Беловская ул", build: "2Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Беловская ул", build: "2к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Весенний пер", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Весенний пер", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Волошиной ул", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Волошиной ул", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Волошиной ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Гастелло ул (Новый городок)", build: "11 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гастелло ул (Новый городок)", build: "19 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гастелло ул (Новый городок)", build: "21 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гастелло ул (Новый городок)", build: "23 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гастелло ул (Новый городок)", build: "27 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гастелло ул (Новый городок)", build: "29 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "10 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "11 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "12 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "13 || Ростелеком: none Билайн: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "14 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "2 || Ростелеком: none Билайн: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "23 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "25 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "27 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "29 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "33 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "35 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "37 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Гражданская ул (Новый городок)", build: "6 || Ростелеком: none Билайн: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Гражданская ул (Новый городок)", build: "8 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Доватора ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Доватора ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "10 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "14 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "16 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "2 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "20 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "21 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Ермака ул (Новый городок)", build: "24 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Ермака ул (Новый городок)", build: "6 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Железнодорожная ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Железнодорожная ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Железнодорожная ул", build: "30 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Железнодорожная ул", build: "32 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "40 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "54 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "56 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Железнодорожная ул", build: "9А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Каховская ул", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "17 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "27 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "29 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "33 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "34 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "35 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "36 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "39 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "41 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "43 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "44 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "47 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "48 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "49 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "51 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "53 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "54 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Киевская ул (Новый городок)", build: "55 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "57 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "59 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Киевская ул (Новый городок)", build: "61 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Клубный пер", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Козлова ул", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "14к.А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "1к.Б || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "26к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "28 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "32к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "36к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "36к.В || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "36к.Г || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "41 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "42 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "49 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "59 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "61 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Ленина ул", build: "67А || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Ленина ул", build: "67к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Люксембург ул", build: "34к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Люксембург ул", build: "34к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Люксембург ул", build: "34к.Г || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Маркса ул", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса ул", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Маркса ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Морозова ул", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Морозова ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Московская ул", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Московская ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Новогодняя ул", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская ул", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская ул", build: "27 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "29 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "31 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "35 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "37 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "39 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "41 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "43 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская ул", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Октябрьская ул", build: "47 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "51 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "53 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "55 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "59 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "63 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Октябрьская ул", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Полярная ул", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Почтовый пер", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Почтовый пер", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Почтовый пер", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Пржевальского ул (Новый городок)", build: "11 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Пржевальского ул (Новый городок)", build: "13 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Пржевальского ул (Новый городок)", build: "14 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Пржевальского ул (Новый городок)", build: "16 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Пржевальского ул (Новый городок)", build: "17 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Пржевальского ул (Новый городок)", build: "19 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Пржевальского ул (Новый городок)", build: "20 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Пржевальского ул (Новый городок)", build: "26 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Пржевальского ул (Новый городок)", build: "9 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Пролетарская ул", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Пролетарская ул", build: "1к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "32 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "33 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "34 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "35 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "36 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "37 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "38 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "39 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "40 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "41В || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "41к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "41к.Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "42 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "43 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "45 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "46 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "47 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "48 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "49 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "50 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "51 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "53 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "55 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "56 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "58 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "62 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "63 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Советская ул", build: "67 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "69 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "71 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советский пер", build: "1к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "2Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сосновый кв-л", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Спортивный пер", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Седова ул (Новый городок)", build: "18 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Седова ул (Новый городок)", build: "20 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Седова ул (Новый городок)", build: "30 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Седова ул (Новый городок)", build: "34 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "36 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "38 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Седова ул (Новый городок)", build: "40 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "48 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "50 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "52 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "54 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "58 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Седова ул (Новый городок)", build: "60 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тельмана ул", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тельмана ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Толстого ул", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "15к.А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Толстого ул", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Толстого ул", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "1 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "10 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "11 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "12 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "12А || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "12Б || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "13 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "14 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "16 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "18 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "2 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "20 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "22 || Ростелеком: Pon Билайн: none", rtk : "Pon", beeline : "none"},
{street: "Тухачевского ул (Новый городок)", build: "3 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "4 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "5 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "6 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "7 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "8 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Тухачевского ул (Новый городок)", build: "9 || Ростелеком: Pon Билайн: ETTH", rtk : "Pon", beeline : "ETTH"},
{street: "Халтурина ул", build: "34в || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Хмельницкого ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской ул", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Цинкзаводской ул", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Цинкзаводской ул", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Цинкзаводской ул", build: "3 || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "ETTH"},
{street: "Цинкзаводской ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Цинкзаводской ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Цинкзаводской ул", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Чкалова ул", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чкалова ул", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная ул", build: "10к.А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная ул", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная ул", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юбилейная ул", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юбилейная ул", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "10А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности ул", build: "11 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности ул", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности ул", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "22 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Юности ул", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "7 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},
{street: "Юности ул", build: "9 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "ETTH"},,],
streets: [{street: "1-Я Боевая ул"},
{street: "3 Й-микрорайон ул"},
{street: "6-Й-микрорайон"},
{street: "Беловская ул"},
{street: "Весенний пер"},
{street: "Волошиной ул"},
{street: "Гастелло ул (Новый городок)"},
{street: "Гражданская ул (Новый городок)"},
{street: "Доватора ул"},
{street: "Ермака ул (Новый городок)"},
{street: "Железнодорожная ул"},
{street: "Каховская ул"},
{street: "Киевская ул (Новый городок)"},
{street: "Клубный пер"},
{street: "Козлова ул"},
{street: "Ленина ул"},
{street: "Люксембург ул"},
{street: "Маркса ул"},
{street: "Морозова ул"},
{street: "Московская ул"},
{street: "Новогодняя ул"},
{street: "Октябрьская ул"},
{street: "Полярная ул"},
{street: "Почтовый пер"},
{street: "Пржевальского ул (Новый городок)"},
{street: "Пролетарская ул"},
{street: "Советская ул"},
{street: "Советский пер"},
{street: "Сосновый кв-л"},
{street: "Спортивный пер"},
{street: "Седова ул (Новый городок)"},
{street: "Тельмана ул"},
{street: "Толстого ул"},
{street: "Тухачевского ул (Новый городок)"},
{street: "Халтурина ул"},
{street: "Хмельницкого ул"},
{street: "Цинкзаводской ул"},
{street: "Чкалова ул"},
{street: "Юбилейная ул"},
{street: "Юности ул"},
]};
