city_streets["kiselevsk"] = {builds: [{street: "1-МАЯ", build: "11А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "11к.1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "11к.2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "11к.3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "13 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "2Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "3 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "3А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "44 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "4А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "58 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "62 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "9Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "1-МАЯ", build: "9к.1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "1-МАЯ", build: "9к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-города", build: "1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "10 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "11 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "11А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "12 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "13 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "14 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "16 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "17 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "18 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "19 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "20 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "22 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "23 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "24 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "25 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "26 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "27 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "28 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "29 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "30 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "31 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "33 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "34 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "35 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "36 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "37 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "39 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "3к.1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "3к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "40 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "41 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "42 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-города", build: "47 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "49 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "5 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "5А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "6 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "8 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-города", build: "9 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "50-лет-октября", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "27А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "29 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "30 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "31 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "32 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "33 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "35 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "36 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "38 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "39к.1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "39к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "40 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "41 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "41к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "43 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "43к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "43к.3 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "45 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "46 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "48 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "50 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "54 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "56 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "58 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "60 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "62 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "64 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "50-лет-октября", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "8А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "50-лет-октября", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БАГРАТИОНА", build: "13 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Багратиона", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Багратиона", build: "17 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Багратиона", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Багратиона", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Багратиона", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Багратиона", build: "25 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Багратиона", build: "34 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "БАГРАТИОНА", build: "37 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Багратиона", build: "38 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "БАГРАТИОНА", build: "41 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "БАГРАТИОНА", build: "42 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЕВАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЕВАЯ", build: "12А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЕВАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЕВАЯ", build: "14А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Боевая", build: "16А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "БОЕВАЯ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Боевая", build: "20 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Боевая", build: "20к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Боевая", build: "22 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "БОЕВАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЕВАЯ", build: "6А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Большая-Дачная", build: "60 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "62 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "63 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "64 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "65 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "67 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Большая-Дачная", build: "69 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "12к.2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "12к.3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "16к.2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "16к.3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "35 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "БОЛЬШЕВИСТСКАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВАХРУШЕВА", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВАХРУШЕВА", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВЕСЕННЯЯ", build: "1 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Весенняя", build: "10 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "11 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "12 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "13 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "14 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "14А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "15 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "16 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "17 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "19 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "29 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ВЕСЕННЯЯ", build: "29А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Весенняя", build: "2к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "31 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "33 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Весенняя", build: "4к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ВОДОПРОВОДНАЯ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ВОДОПРОВОДНАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Гагарина", build: "1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ГАГАРИНА", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "17А || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Гагарина", build: "18 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ГАГАРИНА", build: "19 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Гагарина", build: "20 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ГАГАРИНА", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Гагарина", build: "24 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ГАГАРИНА", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "28 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "29 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "30 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "31 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "33 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ГАГАРИНА", build: "41 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ГОРМАШЕВСКАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "24А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "30 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "32 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДЗЕРЖИНСКОГО", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ДРУЖБЫ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Дружбы", build: "2к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ДРУЖБЫ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАБАЙКАЛЬСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАГАРАЖНАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАПАДНЫЙ", build: "10к.1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАПАДНЫЙ", build: "7к.1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАПАДНЫЙ", build: "7к.2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗАПАДНЫЙ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "35 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "37 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "41 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "43 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "43Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЗЕМЛЯЧКИ", build: "47 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "И.Черных", build: "11А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "И.Черных", build: "13А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "И.ЧЕРНЫХ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "И.ЧЕРНЫХ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "И.Черных", build: "4 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "И.Черных", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "И.Черных", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "И.ЧЕРНЫХ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ИНЖЕНЕРНАЯ", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ИНЖЕНЕРНАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Инженерная", build: "12 || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ИНЖЕНЕРНАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ИНЖЕНЕРНАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ИНЖЕНЕРНАЯ", build: "4А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Инженерная", build: "6А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ИНЖЕНЕРНАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "17Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЗАНСКАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КАЛИНИНА", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРОВА", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "37 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "37А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИРПИЧНЫЙ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИСЕЛЕВСКАЯ", build: "50 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИСЕЛЕВСКАЯ", build: "51 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КИСЕЛЕВСКАЯ", build: "51А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОВАЛЕНКО", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОВАЛЕНКО", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОВАЛЕНКО", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КОМСОМОЛЬСКИЙ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КРАСИНА", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КУЛЬТУРНАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КУЛЬТУРНАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КУЛЬТУРНАЯ", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КУЛЬТУРНАЯ", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "КУЛЬТУРНАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "38 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "39 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Ленина", build: "41 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Ленина", build: "42 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Ленина", build: "43 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЛЕНИНА", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "46А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЛЕНИНА", build: "47 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "49 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЛЕНИНА", build: "51 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "52 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "53 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "54 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ленина", build: "55 || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ЛЕНИНА", build: "56 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "24А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "26А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "28А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "37 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "47 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЛУТУГИНА", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЙКОПСКАЯ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЙКОПСКАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Майкопская", build: "2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "МАЙКОПСКАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Макарова", build: "23 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Макарова", build: "25 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "МАТРОСОВА", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАТРОСОВА", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАТРОСОВА", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАТРОСОВА", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАТРОСОВА", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАТРОСОВА", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Матросова", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Матросова", build: "6 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "МАЯКОВСКОГО", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "15А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МАЯКОВСКОГО", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Мира", build: "10 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "12к.1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "12к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "14 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "16 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "20 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "22 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "24 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "26 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "2к.1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "30 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "32 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "34 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "36 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "38 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "42 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "44 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "46А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "48 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "4к.1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "50 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "52 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "54 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "56к.1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "6 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Мира", build: "8 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "МОСКОВСКАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "24 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "30 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "МОСКОВСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Московская", build: "7 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "МУРМАНСКИЙ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "МУРМАНСКИЙ", build: "22к.2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "НОВОСТРОЙКА", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "НОВОСТРОЙКА", build: "10А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Новостройка", build: "11 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "НОВОСТРОЙКА", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Новостройка", build: "13 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "13А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "НОВОСТРОЙКА", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Новостройка", build: "15 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "НОВОСТРОЙКА", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Новостройка", build: "17 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "НОВОСТРОЙКА", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Новостройка", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "5 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "6 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Новостройка", build: "7 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Новостройка", build: "8 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ОДЕССКАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "14А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "26 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "28 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "48А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОДЕССКАЯ", build: "50А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Охотская", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Охотская", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ОХОТСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ОХОТСКАЯ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПАНФИЛОВА", build: "6А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Пионерская", build: "1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Пионерская", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Пионерская", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Пионерская", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Пионерская", build: "5 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Пионерская", build: "6 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ПОЛЕВАЯ", build: "45 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНЫЙ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНЫЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПРОГРЕССИВНЫЙ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Промышленная", build: "1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ПРОМЫШЛЕННАЯ", build: "1А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Промышленная", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ПРОМЫШЛЕННАЯ", build: "6 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ПУТЕЙСКАЯ", build: "29 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПУТЕЙСКАЯ", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПУТЕЙСКАЯ", build: "44 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПУТЕЙСКАЯ", build: "44А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ПУТЕЙСКАЯ", build: "46 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РАЩУПКИНА", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Ращупкина", build: "10к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Ращупкина", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Ращупкина", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "РАЩУПКИНА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РАЩУПКИНА", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "25 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "27 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "31 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "33 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "РЕЙДОВАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "САДОВАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "САНДАЛОВА", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Сандалова", build: "17 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СЕДОВА", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СОВЕТСКАЯ", build: "12 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "14 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "16А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "24 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СОВЕТСКАЯ", build: "2А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "3А || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Советская", build: "3Б || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СОВЕТСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "4А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Советская", build: "5 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СОВЕТСКАЯ", build: "5А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "8А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СОСНОВАЯ", build: "7 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "СОСНОВАЯ", build: "8 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "СОСНОВАЯ", build: "9 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "СТАВРОПОЛЬСКАЯ", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СТАВРОПОЛЬСКАЯ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "СТАВРОПОЛЬСКАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Строителей", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Строителей", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Строителей", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Строителей", build: "7 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Строителей", build: "9 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Студенческая", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СТУДЕНЧЕСКАЯ", build: "11 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Студенческая", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СТУДЕНЧЕСКАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Студенческая", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "14к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СТУДЕНЧЕСКАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Студенческая", build: "16 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "16к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "18к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "1к.1 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "1к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Студенческая", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "СТУДЕНЧЕСКАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТАЙБИНЦЕВ", build: "36 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОЛСТОГО", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОЛСТОГО", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОЛСТОГО", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОЛСТОГО", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОЛСТОГО", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "10 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Томская", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Томская", build: "16 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ТОМСКАЯ", build: "17 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Томская", build: "18 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ТОМСКАЯ", build: "19 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Томская", build: "25 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ТОМСКАЯ", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "4 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТОМСКАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНАЯ", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНЫЙ", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНЫЙ", build: "4 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ТРАНСПОРТНЫЙ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНЫЙ", build: "8 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "16 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "20 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "22 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "22А || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "22Б || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "23 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТРУДОВАЯ", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТУЛЬСКАЯ", build: "13 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТУЛЬСКАЯ", build: "15 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Тульская", build: "20 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Тульская", build: "21 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Тульская", build: "23 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ТУЛЬСКАЯ", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ТУЛЬСКАЯ", build: "7 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Унжакова", build: "10 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Унжакова", build: "12 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Унжакова", build: "14 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Унжакова", build: "16 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "УНЖАКОВА", build: "18 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Унжакова", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "УНЖАКОВА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "УНЖАКОВА", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "УНЖАКОВА", build: "6 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Унжакова", build: "8 || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "УНЖАКОВА", build: "9 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "УСКАТНАЯ", build: "17 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "17А || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "23 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "25 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "27А || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "33 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "35 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "37 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "4 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "УСКАТНАЯ", build: "5 || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Утренняя", build: "1 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "1А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "4к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "5 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "6 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "6к.2 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "6к.3 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Утренняя", build: "6к.4 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "10А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "10Б || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "10В || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "12А || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "Фадеева", build: "12Б || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ФАДЕЕВА", build: "12к.А || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Фадеева", build: "14Б || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "16А || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "Фадеева", build: "16Б || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ФАДЕЕВА", build: "16к.Б || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Фадеева", build: "6А || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "6Б || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "Фадеева", build: "6В || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ФАДЕЕВА", build: "6к.В || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "Фадеева", build: "8А || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "Фадеева", build: "8Б || Ростелеком: none Билик: ETTH", rtk : "none", beeline : "Билик"},
{street: "ФАДЕЕВА", build: "8к.А || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ФАДЕЕВА", build: "8к.Б || Ростелеком: ETTH Билик: none", rtk : "ETTH", beeline : "none"},
{street: "ЧАЙКОВСКОГО", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Черноморская", build: "17к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "21 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "21к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "23 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "23к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "25к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "27 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "29 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "31 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черноморская", build: "31к.2 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Черняховского", build: "17 || Ростелеком: ETTH Билик: ETTH", rtk : "ETTH", beeline : "Билик"},
{street: "ЧЕРНЯХОВСКОГО", build: "2 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "ЧУМОВА", build: "1 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чумова", build: "15 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Чумова", build: "19 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЧУМОВА", build: "21 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чумова", build: "27 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Чумова", build: "29 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЧУМОВА", build: "3 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},
{street: "Чумова", build: "31 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "Чумова", build: "42 || Ростелеком: PON Билик: ETTH", rtk : "PON", beeline : "Билик"},
{street: "ЧУМОВА", build: "5 || Ростелеком: PON Билик: none", rtk : "PON", beeline : "none"},],
streets: [{street: "1-МАЯ"},
{street: "50-лет-города"},
{street: "50-лет-октября"},
{street: "БАГРАТИОНА"},
{street: "БОЕВАЯ"},
{street: "Большая-Дачная"},
{street: "БОЛЬШЕВИСТСКАЯ"},
{street: "ВАХРУШЕВА"},
{street: "ВЕСЕННЯЯ"},
{street: "ВОДОПРОВОДНАЯ"},
{street: "Гагарина"},
{street: "ГОРМАШЕВСКАЯ"},
{street: "ДЗЕРЖИНСКОГО"},
{street: "ДРУЖБЫ"},
{street: "ЗАБАЙКАЛЬСКАЯ"},
{street: "ЗАГАРАЖНАЯ"},
{street: "ЗАПАДНЫЙ"},
{street: "ЗЕМЛЯЧКИ"},
{street: "И.Черных"},
{street: "ИНЖЕНЕРНАЯ"},
{street: "КАЗАНСКАЯ"},
{street: "КАЛИНИНА"},
{street: "КИРОВА"},
{street: "КИРПИЧНЫЙ"},
{street: "КИСЕЛЕВСКАЯ"},
{street: "КОВАЛЕНКО"},
{street: "КОМСОМОЛЬСКИЙ"},
{street: "КРАСИНА"},
{street: "КУЛЬТУРНАЯ"},
{street: "ЛЕНИНА"},
{street: "ЛУТУГИНА"},
{street: "МАЙКОПСКАЯ"},
{street: "Макарова"},
{street: "МАТРОСОВА"},
{street: "МАЯКОВСКОГО"},
{street: "Мира"},
{street: "МОСКОВСКАЯ"},
{street: "МУРМАНСКИЙ"},
{street: "НОВОСТРОЙКА"},
{street: "ОДЕССКАЯ"},
{street: "Охотская"},
{street: "ПАНФИЛОВА"},
{street: "Пионерская"},
{street: "ПОЛЕВАЯ"},
{street: "ПРОГРЕССИВНАЯ"},
{street: "ПРОГРЕССИВНЫЙ"},
{street: "Промышленная"},
{street: "ПУТЕЙСКАЯ"},
{street: "РАЩУПКИНА"},
{street: "РЕЙДОВАЯ"},
{street: "САДОВАЯ"},
{street: "САНДАЛОВА"},
{street: "СЕДОВА"},
{street: "Советская"},
{street: "СОСНОВАЯ"},
{street: "СТАВРОПОЛЬСКАЯ"},
{street: "Строителей"},
{street: "Студенческая"},
{street: "ТАЙБИНЦЕВ"},
{street: "ТОЛСТОГО"},
{street: "ТОМСКАЯ"},
{street: "ТРАНСПОРТНАЯ"},
{street: "ТРАНСПОРТНЫЙ"},
{street: "ТРУДОВАЯ"},
{street: "ТУЛЬСКАЯ"},
{street: "Унжакова"},
{street: "УСКАТНАЯ"},
{street: "Утренняя"},
{street: "Фадеева"},
{street: "ЧАЙКОВСКОГО"},
{street: "Черноморская"},
{street: "Черняховского"},
{street: "ЧУМОВА"},
] };
