city_streets["miski"] = {builds: [{street: "10-Й-квартал", build: "1 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "10-Й-квартал", build: "1А ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "10-Й-квартал", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "10-Й-квартал", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "11-Й-квартал", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "11-Й-квартал", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "11-Й-квартал", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "10 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "11 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "12 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "13 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "14 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "17 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "18 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "19 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "20 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "21А ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "21Б ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "8 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "17-Й-квартал", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "18-Й-квартал", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "18-Й-квартал", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "18-Й-квартал", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "18-Й-квартал", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "18-Й-квартал", build: "6А ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "4-Й-квартал", build: "12 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "4-Й-квартал", build: "13 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "4-Й-квартал", build: "14 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "4-Й-квартал", build: "16 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "4-Й-квартал", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "50-лет-Пионерии", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "50-лет-Пионерии", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "50-лет-Пионерии", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "50-лет-Пионерии", build: "8 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "8-Й-квартал", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "10 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "5 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "9-Й-квартал", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "9-Й-квартал", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "15 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "21 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "21А ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "22 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "23 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "24 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "25 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "27 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "29 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "31 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вахрушева", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "11 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "13 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "17 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Вокзальная", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Восточная", build: "19 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Восточная", build: "20 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Восточная", build: "37 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "12 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "23 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "31 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "36 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "38 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "40 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Горького", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Комарова", build: "10 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Комарова", build: "16 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Комарова", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Комарова", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузбасская", build: "14 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузбасская", build: "18 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузбасская", build: "20 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кузнецкая", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "11 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "3 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кусургашева", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кутузова", build: "15 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Кутузова", build: "17 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Куюкова", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Куюкова", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Ленина", build: "3 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Ленина", build: "7 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Мира", build: "1 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Мира", build: "13 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Мира", build: "26 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Мира", build: "28 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Мира", build: "30 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Мира", build: "38 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Ноградская", build: "1 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Ноградская", build: "1А ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Ноградская", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Ноградская", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Ноградская", build: "7 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Ноградская", build: "8 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "17 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "7 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "8 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Олимпийская", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Первомайская", build: "26 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Первомайская", build: "28 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Первомайская", build: "30 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Пушкина", build: "11 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Пушкина", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Пушкина", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Пушкина", build: "5 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Серафимовича", build: "12 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Серафимовича", build: "16 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Серафимовича", build: "2 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Серафимовича", build: "6 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Серафимовича", build: "6А ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "28 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "30 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "31 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "34 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "35 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "37 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Советская", build: "39 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "40 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "41 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "42 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "44 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "46 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Советская", build: "48 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Центральная", build: "20 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Центральная", build: "3 ||    Ростелеком: none    Билайн: ETHH", rtk : "none", beeline : "ETHH"},
{street: "Юбилейный", build: "4 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "Юбилейный", build: "9 ||    Ростелеком: PON    Билайн: ETHH", rtk : "PON", beeline : "ETHH"},
{street: "ВАХРУШЕВА", build: "5 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ВАХРУШЕВА", build: "28 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "3 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ГАГАРИНА", build: "9 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "КОМАРОВА", build: "1 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "КОМАРОВА", build: "5 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "КОМАРОВА", build: "38 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "КОМАРОВА", build: "40 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "КУТУЗОВА", build: "21 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНА", build: "10 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЛЕНИНГРАДСКАЯ", build: "1 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "МИРА", build: "3 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "НОГРАДСКАЯ", build: "5 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "НОГРАДСКАЯ", build: "11 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "НОГРАДСКАЯ", build: "24 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ПЕРВОМАЙСКАЯ", build: "9 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ПЕРВОМАЙСКАЯ", build: "11 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ПЕРВОМАЙСКАЯ", build: "29 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "32 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "СОВЕТСКАЯ", build: "36 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "2 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "3 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "4 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "5А ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "7 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТЕПЛИЧНЫЙ", build: "12 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ТРАНСПОРТНАЯ", build: "2А ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЦЕНТРАЛЬНАЯ", build: "59 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЦЕНТРАЛЬНАЯ", build: "61 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЦЕНТРАЛЬНАЯ", build: "63 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЭНЕРГЕТИКОВ", build: "8 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЭНЕРГЕТИКОВ", build: "13 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "ЭНЕРГЕТИКОВ", build: "14 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "2А ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "4 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "5 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "18 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "19 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "18-Й-квартал", build: "20 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "8-Й-квартал", build: "5 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "8-Й-квартал", build: "6 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},
{street: "9-Й-квартал", build: "8 ||    Ростелеком: PON    Билайн: none", rtk : "PON", beeline : "none"},],
streets: [{street: "10-Й-квартал"},
{street: "11-Й-квартал"},
{street: "17-Й-квартал"},
{street: "18-Й-квартал"},
{street: "4-Й-квартал"},
{street: "50-лет-Пионерии"},
{street: "8-Й-квартал"},
{street: "9-Й-квартал"},
{street: "Вахрушева"},
{street: "Вокзальная"},
{street: "Восточная"},
{street: "Горького"},
{street: "Комарова"},
{street: "Кузбасская"},
{street: "Кузнецкая"},
{street: "Кусургашева"},
{street: "Кутузова"},
{street: "Куюкова"},
{street: "Ленина"},
{street: "Мира"},
{street: "Ноградская"},
{street: "Олимпийская"},
{street: "Первомайская"},
{street: "Пушкина"},
{street: "Серафимовича"},
{street: "Советская"},
{street: "Центральная"},
{street: "Юбилейный"},
{street: "ГАГАРИНА"},
{street: "ЛЕНИНГРАДСКАЯ"},
{street: "ТЕПЛИЧНЫЙ"},
{street: "ТРАНСПОРТНАЯ"},
{street: "ЭНЕРГЕТИКОВ"},
] };
